spring:
  #图片上传配置
  servlet:
    multipart:
      #是否启用文件上传功能
      enabled: true
      #指定文件的位置, 没有指定时会自动创建一个临时文件夹
      location: /home/img
      #指定上传文件大小， 默认1M
      max-file-size: 20MB
      #指定multipart / form-data请求允许的最大大小， 默认10M
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mt-platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: sd123456
    db-type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 256
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 127.0.0.1
    password: sd123456
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 2
    database: 2
  mail:
    host: smtp.qq.com
    # 邮箱账号
    username: 460475302@qq.com
    # 授权码
    password: qppxntuoppgtcabe
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          ssl:
            trust: smtp.qq.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
mail:
  fromMail:
    addr: 460475302@qq.com
    title: 【DHExo】验证码

server:
  port: 18081

redis:
  prefix: njm_
  token: token_uid_

img:
  location: /home/img