spring:
  #图片上传配置
  servlet:
    multipart:
      #是否启用文件上传功能
      enabled: true
      #指定上传文件大小， 默认2g
      max-file-size: 5000MB
      #指定multipart / form-data请求允许的最大大小， 默认2g
      max-request-size: 5000MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mt-platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yl123456
    db-type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 256
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: 127.0.0.1
 #   password: sd123456
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 2
    database: 2
  mail:
    host: adam.origenome.com
    # 邮箱账号
    username: mailagent@dhexo.dhtongliang.com
    # 授权码
    password: SVM_1018
    port: 587
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          ssl:
            trust: adam.origenome.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 587
          starttls:
            enable: true
            required: true
mail:
  fromMail:
    addr: mailagent@dhexo.dhtongliang.com
    title: 【DHExo】验证码
#服务端口
server:
  port: 18081

redis:
  prefix: njm_
  token: token_uid_
#图片路径
img:
  location: /home/ec2-user/web/img/
#vcf4路径
vcf:
  file:
    path: /home/ec2-user/web/vcf/
#grakn路径
grakn:
  server:
    address: 127.0.0.1:48555

